### ISSUE TITLE
在github page部署，访问live2d的CORS问题

### ISSUE THREAD

**Issue by imyhxy** [Aermisty/blog#1]
班班你好，

最近浏览到你的网站，感觉模板很好看，特别是右下角的live2d很有趣，然后想用到自己的静态网站上，但是我在本地部署完成的代码推送到github page后，访问`api.dlzhange.com`时会有`CORS`的错误，请问该有解决的方法吗？

**Comment by leirock** [comment]
因为这个 API 是我自己搭建的，并不开放对外使用，所以设置了 CORS 跨域限制。如果你需要使用 Live2D，可以参考 [stevenjoezhang/live2d-widget](https://github.com/stevenjoezhang/live2d-widget#更多-more) 这个项目里的说明自己搭建后端 API。具体地说，我目前使用的 API 文件是来自 [fghrsh/live2d_api](https://github.com/fghrsh/live2d_api)，需要 PHP 环境。另外似乎也有公共的 API 开放使用，你可以看看我给的第二个链接的相关内容找找看。

**Comment by imyhxy** [comment]
好的，感谢感谢:heart:
