### ISSUE TITLE
请教我写了styles.styl后render报错 failed to locate @import file 

### ISSUE THREAD

**Issue by ufoozhenghao** [Aermisty/blog#3]
![image](https://user-images.githubusercontent.com/42081344/117905350-9fac2700-b305-11eb-9bbe-1313ace709ff.png)
在v8.20的next中配置如上图

styles.style内容入下：

```
/* header-隐藏顶部线条 */
.headband {
  display: none;
}

/* header-顶部空白 */
.header, .main-inner {
  margin-top: 10px;

  +mobile() {
    margin-top: 0;
  }
}
```

请问是哪里没配置对吗

**Comment by leirock** [comment]
你先确认一下你的文件后缀是 `.styl` 吗？我看你的描述应该没有大问题，但是因为你具体的源代码我也不清楚，我建议你去 [NexT 那个 repo](https://github.com/next-theme/hexo-theme-next) 提问NexT 主题配置的问题。

**Comment by ufoozhenghao** [comment]
> 你先确认一下你的文件后缀是 `.styl` 吗？我看你的描述应该没有大问题，但是因为你具体的源代码我也不清楚，我建议你去 [NexT 那个 repo](https://github.com/next-theme/hexo-theme-next) 提问NexT 主题配置的问题。

好吧 谢谢
